# Generated by Django 4.0.2 on 2022-03-07 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=100)),
                ('price', models.CharField(default='', max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('person', models.CharField(max_length=100)),
                ('startdate', models.DateField(default='', max_length=100)),
                ('enddate', models.DateField(default='', max_length=100)),
                ('food', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('light', models.CharField(max_length=100)),
                ('flower', models.CharField(max_length=100)),
                ('seet', models.CharField(max_length=100)),
                ('equpment', models.CharField(max_length=100)),
                ('music', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=20)),
                ('eprice', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='new_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
