# Generated by Django 4.0.2 on 2022-03-08 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='new_user',
            table='new_users',
        ),
    ]
