# Generated by Django 4.0.2 on 2022-03-08 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_new_user_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='new_user',
            new_name='new_users',
        ),
        migrations.AlterModelTable(
            name='new_users',
            table=None,
        ),
    ]
